#!/usr/bin/env python3

"""Build a static GitHub Pages bundle for the public Reeb flow viewer.

The output folder is self-contained and can be pushed to a repository named
``reebflowvisualizer.github.io``.  It contains a small landing page with a
dataset selector and one self-contained viewer folder per exported dataset.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
STAGE_07_SCRIPT = SCRIPT_DIR / "unified_sankey_viewer" / "stage_07_unified_sankey_viewer.py"
DEFAULT_DATASET_ROOT = Path("/home/mohit/Desktop/postdoc/timeVaryingReebSpace/hpc/datasets")
DEFAULT_DATASETS = ("torus", "MVK_s1", "MVK_s2")
TEXT_FILE_SUFFIXES = {".html", ".css", ".js", ".json", ".md", ".txt"}
LOCAL_PATH_MARKERS = ("/home/mohit", "/Desktop/postdoc", "timeVaryingReebSpace")
PUBLIC_CSS_VERSION = "pages-adaptive-v1"


@dataclass(frozen=True)
class DatasetSpec:
    dataset_id: str
    label: str
    base_dir: Path
    include_fiber_surfaces: bool = True


def parse_dataset_spec(raw: str, dataset_root: Path) -> DatasetSpec:
    """Parse NAME or NAME=/path entries."""

    if "=" in raw:
        name, path_text = raw.split("=", 1)
        dataset_id = name.strip()
        base_dir = Path(path_text).expanduser().resolve()
    else:
        dataset_id = raw.strip()
        base_dir = (dataset_root / dataset_id).resolve()
    if not dataset_id:
        raise ValueError(f"Invalid dataset spec: {raw!r}")
    return DatasetSpec(
        dataset_id=dataset_id,
        label=dataset_id.replace("_", " "),
        base_dir=base_dir,
        include_fiber_surfaces=dataset_id.lower() != "torus",
    )


def run_stage_07(base_dir: Path) -> None:
    if not STAGE_07_SCRIPT.exists():
        raise FileNotFoundError(f"Cannot find Stage 7 script: {STAGE_07_SCRIPT}")
    subprocess.run(
        [sys.executable, str(STAGE_07_SCRIPT), "--base-dir", str(base_dir)],
        cwd=SCRIPT_DIR,
        check=True,
    )


def viewer_dir_for(base_dir: Path) -> Path:
    return base_dir / "sankey" / "unified_sankey_viewer"


def safe_reset_output_dir(output_dir: Path, *, force: bool) -> None:
    marker = output_dir / ".reebflow_pages_export"
    if output_dir.exists():
        if not force and not marker.exists():
            raise FileExistsError(
                f"{output_dir} already exists and does not look like a previous export. "
                "Use --force to overwrite it."
            )
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    marker.write_text("generated by build_github_pages_site.py\n", encoding="utf-8")


def scrub_path_value(key: str, value: str, dataset: DatasetSpec) -> str:
    if not any(marker in value for marker in LOCAL_PATH_MARKERS):
        return value
    key = key.lower()
    if key in {"base_dir"}:
        return dataset.dataset_id
    if key in {"sheet_image_dir"}:
        return "sheet_images"
    if key in {"fiber_surface_image_dir"}:
        return "fiber_surface_images" if dataset.include_fiber_surfaces else ""
    if key in {"presets"}:
        return "paper_exports/presets"
    if key in {"images"}:
        return "paper_exports/images"
    if key in {"matches"}:
        return "compareSheetShapesCache/results/sheet_shape_matches.json"
    if key in {"overlap"}:
        return "sankey/sheet_overlaps.json"
    if key.endswith("_file") or key in {"rsi_file", "rsijson_file"}:
        return Path(value).name
    return Path(value).name


def scrub_data_for_public_site(obj: Any, dataset: DatasetSpec, parent_key: str = "") -> Any:
    if isinstance(obj, dict):
        cleaned = {
            key: scrub_data_for_public_site(value, dataset, key)
            for key, value in obj.items()
        }
        if parent_key == "":
            meta = cleaned.setdefault("meta", {})
            if isinstance(meta, dict):
                meta["dataset_id"] = dataset.dataset_id
                meta["dataset_name"] = dataset.label
                meta["base_dir"] = dataset.dataset_id
                meta["sheet_image_dir"] = "sheet_images"
                meta["fiber_surface_image_dir"] = (
                    "fiber_surface_images" if dataset.include_fiber_surfaces else ""
                )
                meta["public_export"] = True
        return cleaned
    if isinstance(obj, list):
        return [scrub_data_for_public_site(value, dataset, parent_key) for value in obj]
    if isinstance(obj, str):
        return scrub_path_value(parent_key, obj, dataset)
    return obj


def remove_fiber_surface_references(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {
            key: (None if key == "fiber_surface_image" else remove_fiber_surface_references(value))
            for key, value in obj.items()
        }
    if isinstance(obj, list):
        return [remove_fiber_surface_references(value) for value in obj]
    return obj


def collect_media_references(data: dict[str, Any], *, include_fiber_surfaces: bool) -> set[str]:
    refs: set[str] = set()

    def walk(obj: Any) -> None:
        if isinstance(obj, dict):
            thumbnail = obj.get("thumbnail")
            if isinstance(thumbnail, str) and thumbnail:
                refs.add(thumbnail)
            fiber = obj.get("fiber_surface_image")
            if include_fiber_surfaces and isinstance(fiber, str) and fiber:
                refs.add(fiber)
            for value in obj.values():
                walk(value)
        elif isinstance(obj, list):
            for value in obj:
                walk(value)

    walk(data)
    return refs


def copy_file(src: Path, dst: Path) -> int:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return dst.stat().st_size


def copy_referenced_media(viewer_dir: Path, dataset_dir: Path, refs: set[str]) -> tuple[int, int]:
    count = 0
    total_bytes = 0
    missing: list[str] = []
    for ref in sorted(refs):
        if ref.startswith("/") or ".." in Path(ref).parts:
            missing.append(ref)
            continue
        src = viewer_dir / ref
        if not src.exists():
            missing.append(ref)
            continue
        total_bytes += copy_file(src, dataset_dir / ref)
        count += 1
    if missing:
        preview = ", ".join(missing[:8])
        suffix = "" if len(missing) <= 8 else f", ... ({len(missing)} missing)"
        print(f"Warning: missing media in {viewer_dir}: {preview}{suffix}", file=sys.stderr)
    return count, total_bytes


def assert_no_local_paths(path: Path) -> None:
    for file_path in path.rglob("*"):
        if not file_path.is_file() or file_path.suffix.lower() not in TEXT_FILE_SUFFIXES:
            continue
        text = file_path.read_text(encoding="utf-8", errors="ignore")
        for marker in LOCAL_PATH_MARKERS:
            if marker in text:
                raise RuntimeError(f"Local path marker {marker!r} remains in {file_path}")


def largest_files(path: Path, limit: int = 8) -> list[tuple[int, Path]]:
    files = [(file_path.stat().st_size, file_path) for file_path in path.rglob("*") if file_path.is_file()]
    files.sort(reverse=True)
    return files[:limit]


def human_size(num_bytes: int) -> str:
    value = float(num_bytes)
    for unit in ("B", "KiB", "MiB", "GiB"):
        if value < 1024 or unit == "GiB":
            return f"{value:.1f} {unit}" if unit != "B" else f"{int(value)} B"
        value /= 1024
    return f"{num_bytes} B"


def write_dataset_loader_index(output_dir: Path, manifest: list[dict[str, Any]]) -> None:
    manifest_json = json.dumps(manifest, indent=2)
    (output_dir / "datasets").mkdir(exist_ok=True)
    (output_dir / "datasets" / "manifest.json").write_text(manifest_json + "\n", encoding="utf-8")
    default_dataset = manifest[0]["id"] if manifest else ""
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Reeb Flow Visualizer</title>
  <style>
    :root {{
      color-scheme: light;
      font-family: Arial, Helvetica, sans-serif;
      background: #f8fafc;
      color: #111827;
    }}
    body {{
      margin: 0;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 12px;
    }}
    header {{
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 6px 14px;
      background: #ffffff;
      border: 1px solid #dbe3ec;
      border-radius: 8px;
      box-shadow: 0 1px 2px rgba(15, 23, 42, 0.06);
    }}
    label {{
      display: inline-flex;
      align-items: center;
      gap: 8px;
      font-size: 13px;
      color: #111827;
    }}
    select {{
      height: 30px;
      border: 1px solid #cbd5e1;
      border-radius: 5px;
      background: #fff;
      color: #111827;
      padding: 0 8px;
    }}
    p {{
      margin: 0;
      font-size: 13px;
      color: #64748b;
    }}
  </style>
</head>
<body>
  <header>
    <label>
      Dataset
      <select id="datasetSelect"></select>
    </label>
  </header>
  <p>Opening dataset viewer...</p>
  <script>
    const DATASETS = {manifest_json};
    const select = document.getElementById("datasetSelect");
    const params = new URLSearchParams(window.location.search);
    const requested = params.get("dataset") || "{default_dataset}";

    for (const dataset of DATASETS) {{
      const option = document.createElement("option");
      option.value = dataset.id;
      option.textContent = dataset.label;
      select.appendChild(option);
    }}

    function openDataset(id) {{
      const dataset = DATASETS.find(item => item.id === id) || DATASETS[0];
      if (!dataset) return;
      select.value = dataset.id;
      window.location.replace(`datasets/${{dataset.id}}/index.html`);
    }}

    select.addEventListener("change", () => openDataset(select.value));
    openDataset(requested);
  </script>
</body>
</html>
"""
    (output_dir / "index.html").write_text(html, encoding="utf-8")


def public_dataset_selector_markup(manifest: list[dict[str, Any]], current_id: str) -> str:
    options = "\n".join(
        f'          <option value="{item["id"]}"{" selected" if item["id"] == current_id else ""}>{item["label"]}</option>'
        for item in manifest
    )
    return f"""<div class="dataset-switcher">
        <label>
          Dataset
          <select id="datasetSelect">
{options}
          </select>
        </label>
      </div>"""


def public_dataset_selector_script(manifest: list[dict[str, Any]], current_id: str) -> str:
    manifest_json = json.dumps([
        {"id": item["id"], "label": item["label"]}
        for item in manifest
    ], separators=(",", ":"))
    return f"""  <script>
    (() => {{
      const DATASETS = {manifest_json};
      const CURRENT_DATASET = {json.dumps(current_id)};
      const select = document.getElementById("datasetSelect");
      if (!select) return;
      select.addEventListener("change", () => {{
        const dataset = DATASETS.find(item => item.id === select.value);
        if (!dataset || dataset.id === CURRENT_DATASET) return;
        window.location.href = `../${{dataset.id}}/index.html`;
      }});
    }})();
  </script>
"""


def inject_dataset_selector(dataset_dir: Path, manifest: list[dict[str, Any]], current_id: str) -> None:
    index_path = dataset_dir / "index.html"
    style_path = dataset_dir / "style.css"
    html = index_path.read_text(encoding="utf-8")
    selector = public_dataset_selector_markup(manifest, current_id)
    script = public_dataset_selector_script(manifest, current_id)

    html = re.sub(
        r'href="style\.css(?:\?v=[^"]*)?"',
        f'href="style.css?v={PUBLIC_CSS_VERSION}"',
        html,
        count=1,
    )
    html = html.replace("<body>", '<body class="public-page">', 1)
    html = html.replace("<header>", '<header class="public-header">', 1)
    html = re.sub(
        r"(<div class=\"title-block\">.*?</div>)",
        f"\\1\n      {selector}",
        html,
        count=1,
        flags=re.S,
    )
    html = html.replace("</body>", script + "</body>", 1)
    index_path.write_text(html, encoding="utf-8")

    public_css = """

/* Public GitHub Pages dataset selector. */
body.public-page header.public-header {
  position: relative;
}
body.public-page .dataset-switcher {
  left: 50%;
  position: absolute;
  top: 50%;
  transform: translate(-50%, -50%);
}
body.public-page .dataset-switcher label {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin: 0;
  font-size: 13px;
  color: #111827;
}
body.public-page .dataset-switcher select {
  height: 30px;
  min-width: 110px;
}
"""
    style_path.write_text(style_path.read_text(encoding="utf-8") + public_css, encoding="utf-8")


def inject_dataset_selectors(output_dir: Path, manifest: list[dict[str, Any]]) -> None:
    for item in manifest:
        inject_dataset_selector(output_dir / "datasets" / item["id"], manifest, item["id"])


def copy_dataset_viewer(dataset: DatasetSpec, output_dir: Path) -> dict[str, Any]:
    viewer_dir = viewer_dir_for(dataset.base_dir)
    if not viewer_dir.exists():
        raise FileNotFoundError(f"Viewer has not been built for {dataset.dataset_id}: {viewer_dir}")

    dataset_dir = output_dir / "datasets" / dataset.dataset_id
    dataset_dir.mkdir(parents=True, exist_ok=True)

    for name in ("index.html", "viewer.js", "viewer_common.js", "style.css"):
        copy_file(viewer_dir / name, dataset_dir / name)

    data = json.loads((viewer_dir / "data.json").read_text(encoding="utf-8"))
    if not dataset.include_fiber_surfaces:
        data = remove_fiber_surface_references(data)
    data = scrub_data_for_public_site(data, dataset)
    media_refs = collect_media_references(
        data,
        include_fiber_surfaces=dataset.include_fiber_surfaces,
    )
    media_count, media_bytes = copy_referenced_media(viewer_dir, dataset_dir, media_refs)

    data_path = dataset_dir / "data.json"
    data_path.write_text(json.dumps(data, separators=(",", ":")), encoding="utf-8")

    total_bytes = sum(file_path.stat().st_size for file_path in dataset_dir.rglob("*") if file_path.is_file())
    return {
        "id": dataset.dataset_id,
        "label": dataset.label,
        "path": f"datasets/{dataset.dataset_id}/index.html",
        "timesteps": data.get("meta", {}).get("timesteps"),
        "media_files": media_count,
        "media_size_bytes": media_bytes,
        "dataset_size_bytes": total_bytes,
        "includes_fiber_surfaces": dataset.include_fiber_surfaces,
    }


def write_readme(output_dir: Path, manifest: list[dict[str, Any]]) -> None:
    lines = [
        "# Reeb Flow Visualizer",
        "",
        "Datasets can be changed from `torus`, `MVK_s1`, and `MVK_s2` using the dropdown above.",
    ]
    (output_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


def warn_about_large_files(output_dir: Path) -> None:
    for size, file_path in largest_files(output_dir):
        if size >= 50 * 1024 * 1024:
            print(f"Warning: large file {human_size(size)} {file_path.relative_to(output_dir)}")
        if size >= 100 * 1024 * 1024:
            raise RuntimeError(
                f"GitHub blocks files over 100 MiB: {file_path} is {human_size(size)}"
            )


def build_site(args: argparse.Namespace) -> None:
    dataset_root = args.dataset_root.expanduser().resolve()
    dataset_args = args.dataset if args.dataset else list(DEFAULT_DATASETS)
    datasets = [parse_dataset_spec(raw, dataset_root) for raw in dataset_args]
    output_dir = args.output_dir.expanduser().resolve()

    for dataset in datasets:
        if not dataset.base_dir.exists():
            raise FileNotFoundError(f"Dataset not found: {dataset.base_dir}")

    safe_reset_output_dir(output_dir, force=args.force)
    (output_dir / ".nojekyll").write_text("", encoding="utf-8")

    manifest: list[dict[str, Any]] = []
    for dataset in datasets:
        if not args.skip_viewer_rebuild:
            print(f"Building viewer assets for {dataset.dataset_id}...")
            run_stage_07(dataset.base_dir)
        print(f"Copying {dataset.dataset_id}...")
        manifest.append(copy_dataset_viewer(dataset, output_dir))

    inject_dataset_selectors(output_dir, manifest)
    write_dataset_loader_index(output_dir, manifest)
    write_readme(output_dir, manifest)
    assert_no_local_paths(output_dir)
    warn_about_large_files(output_dir)

    total_bytes = sum(file_path.stat().st_size for file_path in output_dir.rglob("*") if file_path.is_file())
    print(f"\nWrote {output_dir}")
    print(f"Total export size: {human_size(total_bytes)}")
    for item in manifest:
        print(
            f"  {item['id']}: {human_size(int(item['dataset_size_bytes']))}, "
            f"{item['media_files']} media files"
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a self-contained GitHub Pages site for the Reeb flow visualizer."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=SCRIPT_DIR / "github_pages_site",
        help="Output folder to create. Default: ./github_pages_site",
    )
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=DEFAULT_DATASET_ROOT,
        help=f"Dataset root. Default: {DEFAULT_DATASET_ROOT}",
    )
    parser.add_argument(
        "--dataset",
        action="append",
        default=None,
        help=(
            "Dataset to export, as NAME or NAME=/absolute/path. "
            "May be repeated. Default: torus, MVK_s1, MVK_s2."
        ),
    )
    parser.add_argument(
        "--skip-viewer-rebuild",
        action="store_true",
        help="Copy existing unified viewer folders instead of rebuilding Stage 7 first.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing output folder even if it does not contain the export marker.",
    )
    args = parser.parse_args()
    build_site(args)


if __name__ == "__main__":
    main()
